---
- name: Install PHP packages
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - php7.0-common
    - php7.0-fpm
    - php7.0-cli
    - php7.0-bcmath
    - php7.0-intl
    - php7.0-curl
    - php7.0-gd
    - php7.0-soap
    - php7.0-json
    - php7.0-mcrypt
    - php7.0-zip
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xml
    - php-imagick

- name: Test is Apache Web Server
  stat: path=/var/www/html/
  register: isApacheDir

- name: install PHP module for apache2
  become: yes
  apt: name=libapache2-mod-php update_cache=yes state=latest
  when: isApacheDir.stat.exists


