---
- include: install-php7.yml
- include: config.yml


- name: Check if composer is installed
  stat: path=/usr/local/bin/composer
  register: composer_bin_file

- include: composer.yml
  when: composer_bin_file.stat.exists == False
